name: Lighthouse

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Lighthouse
      run: lighthouse https://shimmy-rukundo.github.io/home/ --output html
